/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.java;

import static org.junit.Assert.assertEquals;
import static org.junit.Assume.assumeNoException;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

import org.junit.Test;

import parking.lot.java.exception.CommandLineException;
import parking.lot.java.exception.ParkingException;
import parking.lot.java.ui.CommandLine;

public class CommandLineTest {
    /**
     * 
     */
    @Test public void TestReadInputFile_WithValidFilePath() {
        try {
        // Given
            Scanner scanner = new Scanner(new File("src/test/resources/files/valid_test_file"));
        // When
            CommandLine commandLine = new CommandLine(scanner);
            commandLine.run();
        // Then
        } catch (FileNotFoundException | CommandLineException | ParkingException e) {
            assumeNoException(e);
        }
    }

    @Test public void TestReadInputFile_WithINvalidFilePath() {
        try {
        // Given
        Scanner scanner = new Scanner(new File("src/test/resources/files/invalid_test_file"));
        // Then
        } catch (FileNotFoundException e) {
            assertEquals("src/test/resources/files/invalid_test_file (No such file or directory)", e.getMessage());
        }
    }
}
