/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.java;

import java.util.Scanner;

import parking.lot.java.ui.CommandLine;

public class App {
    public static void main(String[] args) {
        CommandLine commandLine = new CommandLine(new Scanner(System.in));
        commandLine.run();
    }
}
