/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package parking.lot.java;

import java.util.Scanner;

import parking.lot.java.cmd.ParkingLotCommand;

public class App {
    public static void main(String[] args) {
        ParkingLotCommand commandLine = new ParkingLotCommand(new Scanner(System.in));
        commandLine.run();
    }
}
